services:
  app:
    container_name: qr-code-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - app:/var/www/html
    ports:
      - 9000:9000
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    container_name: qr-code-nginx
    image: nginx:1.27-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - app:/var/www/html
    depends_on:
      - app

  db:
    container_name: qr-code-db
    image: mysql:8.0.43
    ports:
      - 3307:3306
    env_file:
      - .db.env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  app:
